### ISSUE TITLE
Error when importing model

### ISSUE THREAD

**Issue by pp2amd6** [ultrahacx/Sollumz-RDR#16]
## Description

Error when importing model (XML) from CodeX.

## Preconditions

1. Codex
    1.1 Open CodeX 0.25 from Dexyfex
    1.2 Select and export model
2. Blender ([4.0.0](https://download.blender.org/release/Blender4.0/), [4.0.2](https://download.blender.org/release/Blender4.0/))
2.1 Download latest [Sollumz-RDR](https://github.com/ultrahacx/Sollumz-RDR/archive/refs/heads/main.zip) plugin version (2.4.2)
2.2 In Blender menu select Edit - Preferences
2.3 In opened window select Add-ons in side menu
2.4 Press Install butoon, select archive with downloaded plugin 
2.5 Enable plugin
![image](https://github.com/user-attachments/assets/5fbc6b43-4639-4e00-ae7f-50dd4a8f7b6c)

## Steps to reproduce
1. Open Blender
2. In Blender menu select File - Import - Codewalker XML
3. Select XML file

XML for testing: [r_05__hd_0_2_3.ydr.zip](https://github.com/user-attachments/files/16735788/r_05__hd_0_2_3.ydr.zip)

## Actual result

Import error appeared
![image](https://github.com/user-attachments/assets/b6362c3d-e5c8-475d-a754-0c51d31784b3)

```log
Error importing: D:\Work\RedM\3D\border\landscape\r_05__hd_0_2_3.ydr.xml 
 Traceback (most recent call last):
  File "C:\Users\pp2amd6\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz-RDR-6eba650ecbfd9a4b07f946a3fe2be8fd89024079\sollumz_operators.py", line 93, in execute_timed
    import_ydr(filepath)
  File "C:\Users\pp2amd6\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz-RDR-6eba650ecbfd9a4b07f946a3fe2be8fd89024079\ydr\ydrimport.py", line 33, in import_ydr
    ydr_xml = YDR.from_xml_file(filepath)
  File "C:\Users\pp2amd6\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz-RDR-6eba650ecbfd9a4b07f946a3fe2be8fd89024079\cwxml\drawable.py", line 79, in from_xml_file
    return Drawable(gameTag).from_xml_file(filepath)
  File "C:\Users\pp2amd6\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz-RDR-6eba650ecbfd9a4b07f946a3fe2be8fd89024079\cwxml\element.py", line 92, in from_xml_file
    return cls.from_xml(element_tree.getroot())
  File "C:\Users\pp2amd6\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz-RDR-6eba650ecbfd9a4b07f946a3fe2be8fd89024079\cwxml\drawable.py", line 909, in from_xml
    new = super().from_xml(element)
  File "C:\Users\pp2amd6\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz-RDR-6eba650ecbfd9a4b07f946a3fe2be8fd89024079\cwxml\element.py", line 116, in from_xml
    setattr(new, prop_name, type(obj_element).from_xml(child))
  File "C:\Users\pp2amd6\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz-RDR-6eba650ecbfd9a4b07f946a3fe2be8fd89024079\cwxml\element.py", line 116, in from_xml
    setattr(new, prop_name, type(obj_element).from_xml(child))
  File "C:\Users\pp2amd6\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz-RDR-6eba650ecbfd9a4b07f946a3fe2be8fd89024079\cwxml\element.py", line 224, in from_xml
    new.value.append(new.list_type.from_xml(child))
  File "C:\Users\pp2amd6\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz-RDR-6eba650ecbfd9a4b07f946a3fe2be8fd89024079\cwxml\element.py", line 116, in from_xml
    setattr(new, prop_name, type(obj_element).from_xml(child))
  File "C:\Users\pp2amd6\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz-RDR-6eba650ecbfd9a4b07f946a3fe2be8fd89024079\cwxml\element.py", line 224, in from_xml
    new.value.append(new.list_type.from_xml(child))
  File "C:\Users\pp2amd6\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz-RDR-6eba650ecbfd9a4b07f946a3fe2be8fd89024079\cwxml\element.py", line 116, in from_xml
    setattr(new, prop_name, type(obj_element).from_xml(child))
  File "C:\Users\pp2amd6\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz-RDR-6eba650ecbfd9a4b07f946a3fe2be8fd89024079\cwxml\drawable_RDR.py", line 175, in from_xml
    a = new._load_data_from_str(element.text)
  File "C:\Users\pp2amd6\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz-RDR-6eba650ecbfd9a4b07f946a3fe2be8fd89024079\cwxml\drawable_RDR.py", line 148, in _load_data_from_str
    a = np.loadtxt(io.StringIO(_str), dtype=struct_dtype)
  File "D:\Program Files\Blender 4.0\4.0\python\lib\site-packages\numpy\lib\npyio.py", line 1338, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "D:\Program Files\Blender 4.0\4.0\python\lib\site-packages\numpy\lib\npyio.py", line 999, in _read
    arr = _load_from_filelike(
ValueError: the number of columns changed from 29 to 26 at row 1; use `usecols` to select a subset and avoid this error
```

## Expected result

XML was imported winthout any errors

## Additional context

Model imported without problem on plugin 2.3.1 version
![image](https://github.com/user-attachments/assets/41d76a2d-cb2c-46a4-b0b4-466cf24e32c0)

**Comment by ultrahacx** [comment]
If you are using latest Sollumz-RDR then you need to use CodeX-026 and export XML from that version since there were some changes related to XML in CodeX-206

**Comment by pp2amd6** [comment]
> If you are using latest Sollumz-RDR then you need to use CodeX-026 and export XML from that version since there were some changes related to XML in CodeX-206

Oh. Thanks for reply! I`ll try Codex 0.26 later.
I will close issue for now.
